In [59]:
import pandas as pd

In [82]:
# Load the csv.
df = pd.read_csv("bank.csv")
# Export as .xlsx file.
df.to_excel("bank.xlsx", index=False)

# ⚙️ Preprocessing

In [83]:
unnecessary_features = [
    'age', 'default', 'contact', 'day', 'month', 'duration',
    'campaign', 'pdays', 'previous', 'poutcome', 'deposit'
]
df = df.drop(columns=unnecessary_features)

In [84]:
df.head(10)

          job   marital  education  balance housing loan
0      admin.   married  secondary     2343     yes   no
1      admin.   married  secondary       45      no   no
2  technician   married  secondary     1270     yes   no
3    services   married  secondary     2476     yes   no
4      admin.   married   tertiary      184      no   no
5  management    single   tertiary        0     yes  yes
6  management   married   tertiary      830     yes  yes
7     retired  divorced  secondary      545     yes   no
8  technician   married  secondary        1     yes   no
9    services    single  secondary     5090     yes   no

In [85]:
df_bak = df.copy()

## 📇 Job

In [86]:
print(df['job'].nunique())

12

In [87]:
print(df['job'].value_counts())

job
management       2566
blue-collar      1944
technician       1823
admin.           1334
services          923
retired           778
self-employed     405
student           360
unemployed        357
entrepreneur      328
housemaid         274
unknown            70
Name: count, dtype: int64

In [88]:
df['job'].sample(10)

6430        management
1036        technician
9993        management
7605          services
1020       blue-collar
246          housemaid
10802       management
4234     self-employed
10089      blue-collar
4513        technician
Name: job, dtype: object

### 💼 JOB => stability score

In [89]:
df1 = df.copy()

In [90]:
job_stability_map = {
    'management': 0.9,
    'technician': 0.85,
    'admin.': 0.8,
    'services': 0.65,
    'blue-collar': 0.6,
    'self-employed': 0.55,
    'entrepreneur': 0.5,
    'housemaid': 0.45,
    'retired': 0.7,
    'student': 0.3,
    'unemployed': 0.1,
    'unknown': 0.5
}

df1["job_stability_score"] = df1["job"].map(job_map).fillna(0.5)
df1.drop(columns=["job"], inplace=True)

In [91]:
df1['job_stability_score'].sample(7)

5667     0.5
1294     0.2
4364     0.7
5591     0.5
2940     0.5
1217     0.8
10868    0.9
Name: job_stability_score, dtype: float64

## 💍Marital status

In [92]:
df2 = df1.copy()

In [93]:
print(df2['marital'].value_counts())

marital
married     6351
single      3518
divorced    1293
Name: count, dtype: int64

In [94]:
df2 = pd.get_dummies(df, columns=['marital'], dtype=int)

In [95]:
df2.head()

,job,education,balance,housing,loan,marital_divorced,marital_married,marital_single
0,admin.,secondary,2343,yes,no,0,1,0
1,admin.,secondary,45,no,no,0,1,0
2,technician,secondary,1270,yes,no,0,1,0
3,services,secondary,2476,yes,no,0,1,0
4,admin.,tertiary,184,no,no,0,1,0

## 🎓 Educational qualification

In [96]:
df3 = df2.copy()

In [97]:
print(df3['education'].value_counts())

education
secondary    5476
tertiary     3689
primary      1500
unknown       497
Name: count, dtype: int64

In [98]:
df3 = pd.get_dummies(df, columns=["education"],  dtype=int, drop_first=True)

In [99]:
df3.columns

Index(['job', 'marital', 'balance', 'housing', 'loan', 'education_secondary',
       'education_tertiary', 'education_unknown'],
      dtype='object')

In [79]:
education = ['education_secondary', 'education_tertiary', 'education_unknown']
df[education].head()

   education_secondary  education_tertiary  education_unknown
0                 True               False              False
1                 True               False              False
2                 True               False              False
3                 True               False              False
4                False                True              False

## 💸 Balance

In [12]:
print("Maximum balance: ",df['balance'].max(),"\nMinimum balance: ",df['balance'].min())

Maximum balance:  81204
Minimum balance:  -6847

In [13]:
df.rename(columns={'balance': 'avg_balance'}, inplace=True)

## 🏠💰 Housing loan and Other loans

In [14]:
df['housing'].value_counts()

housing
no     5881
yes    5281
Name: count, dtype: int64

In [16]:
df[['housing', 'loan']] = df[['housing', 'loan']].replace({'yes': 1, 'no': 0})

In [20]:
df.head(10)

,job,education,avg_balance,housing,loan,marital_divorced,marital_married,marital_single
0,admin.,secondary,2343,1,0,0,1,0
1,admin.,secondary,45,0,0,0,1,0
2,technician,secondary,1270,1,0,0,1,0
3,services,secondary,2476,1,0,0,1,0
4,admin.,tertiary,184,0,0,0,1,0
5,management,tertiary,0,1,1,0,0,1
6,management,tertiary,830,1,1,0,1,0
7,retired,secondary,545,1,0,1,0,0
8,technician,secondary,1,1,0,0,1,0
9,services,secondary,5090,1,0,0,0,1

# new intoduced features

In [21]:
import numpy as np

## 💳 Financial Features

In [22]:
df["monthly_income_avg"] = np.random.randint(8000, 60000, len(df))
df["annual_income"] = df["monthly_income_avg"] * 12

df["income_variance"] = np.random.uniform(0.1, 0.7, len(df))

In [23]:
df.head(10)

,job,education,avg_balance,housing,loan,marital_divorced,marital_married,marital_single,monthly_income_avg,annual_income,income_variance
0,admin.,secondary,2343,1,0,0,1,0,50936,611232,0.265657
1,admin.,secondary,45,0,0,0,1,0,28492,341904,0.544040
2,technician,secondary,1270,1,0,0,1,0,52986,635832,0.562075
3,services,secondary,2476,1,0,0,1,0,38817,465804,0.223364
4,admin.,tertiary,184,0,0,0,1,0,14199,170388,0.494538
5,management,tertiary,0,1,1,0,0,1,56996,683952,0.165599
6,management,tertiary,830,1,1,0,1,0,45802,549624,0.603766
7,retired,secondary,545,1,0,1,0,0,58503,702036,0.373494
8,technician,secondary,1,1,0,0,1,0,38520,462240,0.312872
9,services,secondary,5090,1,0,0,0,1,45006,540072,0.463877

## 📊 Seasonality & Event Features

In [26]:
# simulate seasonal workers
seasonal_flag = np.random.choice([0,1], size=len(df), p=[0.6,0.4])

df["seasonality_score"] = np.where(seasonal_flag==1,
                                  np.random.uniform(0.6,1.0,len(df)),
                                  np.random.uniform(0.0,0.4,len(df)))

df["income_concentration"] = np.where(seasonal_flag==1,
                                      np.random.uniform(0.5,0.9,len(df)),
                                      np.random.uniform(0.1,0.4,len(df)))

df["event_dependence_score"] = df["seasonality_score"]

In [29]:
seasonal_features = [
    'seasonality_score',
    'income_concentration',
    'event_dependence_score'
]
df[seasonal_features].head(10)

   seasonality_score  income_concentration  event_dependence_score
0           0.123854              0.166920                0.123854
1           0.136856              0.260171                0.136856
2           0.926581              0.543304                0.926581
3           0.344947              0.308959                0.344947
4           0.013565              0.127076                0.013565
5           0.760119              0.781033                0.760119
6           0.624919              0.653144                0.624919
7           0.270994              0.352199                0.270994
8           0.824937              0.637810                0.824937
9           0.195483              0.346640                0.195483

## 🧾 Behavioral Features

In [30]:
df["bill_payment_score"] = np.random.uniform(0,1,len(df))
df["upi_txn_count"] = np.random.randint(10,300,len(df))

df["ecommerce_spend"] = np.random.randint(500,20000,len(df))
df["ecommerce_spend_ratio"] = df["ecommerce_spend"] / df["monthly_income_avg"]

In [31]:
behavioral_features = [
    'bill_payment_score',
    'upi_txn_count',
    'ecommerce_spend',
    'ecommerce_spend_ratio'
]
df[behavioral_features].head(10)

   bill_payment_score  upi_txn_count  ecommerce_spend  ecommerce_spend_ratio
0            0.474722            290             7114               0.139665
1            0.456859             92            18819               0.660501
2            0.153492            283            13355               0.252048
3            0.664621            151             5359               0.138058
4            0.335247             58             6174               0.434819
5            0.120624            152             1086               0.019054
6            0.710927            229            15954               0.348325
7            0.996390            236             9346               0.159752
8            0.745709            268            15975               0.414720
9            0.924695            110             9977               0.221682

## 📍Location Stability

In [32]:
df["location_stability"] = np.random.uniform(0,1,len(df))

In [35]:
df["location_stability"].head(10)

0    0.129249
1    0.090937
2    0.677505
3    0.982209
4    0.394131
5    0.918627
6    0.938171
7    0.996579
8    0.317741
9    0.578200
Name: location_stability, dtype: float64

In [40]:
df["job_stability_score"].sample(10)

3685    0.6
5001    0.6
3281    0.5
8049    0.5
9046    0.5
4107    0.9
2981    0.2
3268    0.7
1881    0.7
9057    0.9
Name: job_stability_score, dtype: float64

🧠 Psychometric (disabled now)

In [41]:
# df["questionnaire_score"] = np.random.uniform(0,1,len(df))

## ⭐ Trust

In [43]:
df["merchant_rating"] = np.random.uniform(1,5,len(df))

In [44]:
df["merchant_rating"].head(10)

0    1.830388
1    4.853699
2    2.666449
3    4.837321
4    1.870529
5    2.401130
6    2.257901
7    2.096220
8    4.429781
9    3.076956
Name: merchant_rating, dtype: float64

# 🎯 Target

In [45]:
risk = (
    0.20 * df["income_variance"] * (1 - df["seasonality_score"]) +
    0.20 * (1 - df["bill_payment_score"]) +
    0.15 * (1 - df["location_stability"]) +
    # 0.15 * (1 - df["questionnaire_score"]) +
    0.10 * df["ecommerce_spend_ratio"] +
    0.10 * (1 - df["job_stability_score"]) +
    0.10 * (df["income_concentration"] * (1 - df["event_dependence_score"]))
)

df["default"] = (risk > 0.5).astype(int)

In [53]:
for column in list(df.columns):
    print(column)

job
education
avg_balance
housing
loan
marital_divorced
marital_married
marital_single
monthly_income_avg
annual_income
income_variance
seasonality_score
income_concentration
event_dependence_score
bill_payment_score
upi_txn_count
ecommerce_spend
ecommerce_spend_ratio
location_stability
job_stability_score
merchant_rating
default

In [47]:
print(df.shape)

(11162, 22)

In [48]:
# import packages.
import pandas as pd
import numpy as np

In [51]:
'''Exported dataset files.'''
# df.to_excel("bank1.xlsx", index=False)
# df.to_excel("bank2.xlsx", index=False)
# df.to_excel("bank3.xlsx", index=False)
df.to_csv("bank3.csv", index=False)